extends: ./src/index.js

env:
  node: true

overrides:
  - files: ./tests/flow.js
    extends: ./src/flow.js

  - files: ./tests/react.js
    extends: ./src/react.js

  - files: ./tests/react-native.js
    extends:
      - ./src/flow.js
      - ./src/react-native.js
